apiVersion: v1
kind: Pod
metadata:
  name: smppsim
  labels:
    name: smppsim
spec:
  hostname: smppsim
  containers:
  - name: smppsim
    image: jookies/smppsim:latest
---
apiVersion: v1
kind: Service
metadata:
  name: smpp-simulator
spec:
  selector:
    name: smppsim
  clusterIP: None
