apiVersion: 1

datasources:
  - name: Prometheus
    uid: jasmin-prometheus-ds
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    editable: false
    enabled: true
    version: 1
